#!/bin/bash
# /etc/init.d/podio

### BEGIN INIT INFO
# Provides:          podio
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: bootscript for podio
# Description:       This service is used to start podio
### END INIT INFO


case "$1" in 
    start)
        echo "Starting podio"
        /home/pi/podio.sh
        ;;
    stop)
        echo "Stopping servoblaster"
        killall podio
        ;;
    *)
        echo "Usage: /etc/init.d/podio start|stop"
        exit 1
        ;;
esac

exit 0
